// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2yOvkPoacTl1jBQa6LySMc2N3qz4wTls',
    appId: '1:50575165484:web:dd21c75bfdbdc4cb6e2989',
    messagingSenderId: '50575165484',
    projectId: 'ipl-auction-app-d2984',
    authDomain: 'ipl-auction-app-d2984.firebaseapp.com',
    storageBucket: 'ipl-auction-app-d2984.firebasestorage.app',
    measurementId: 'G-YCHT9W4QWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8boWr1LEG3IxLNJqfD-l-8K21R9Cbs6w',
    appId: '1:50575165484:android:b7ca2f812daa58d46e2989',
    messagingSenderId: '50575165484',
    projectId: 'ipl-auction-app-d2984',
    storageBucket: 'ipl-auction-app-d2984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrK2v4RTBxl-Jvr9fIGvvD8wl9WpXbFeM',
    appId: '1:50575165484:ios:a9a8bf34722c52e56e2989',
    messagingSenderId: '50575165484',
    projectId: 'ipl-auction-app-d2984',
    storageBucket: 'ipl-auction-app-d2984.firebasestorage.app',
    iosBundleId: 'com.example.iplAuctionPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrK2v4RTBxl-Jvr9fIGvvD8wl9WpXbFeM',
    appId: '1:50575165484:ios:a9a8bf34722c52e56e2989',
    messagingSenderId: '50575165484',
    projectId: 'ipl-auction-app-d2984',
    storageBucket: 'ipl-auction-app-d2984.firebasestorage.app',
    iosBundleId: 'com.example.iplAuctionPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2yOvkPoacTl1jBQa6LySMc2N3qz4wTls',
    appId: '1:50575165484:web:a09fabfa77fe21b56e2989',
    messagingSenderId: '50575165484',
    projectId: 'ipl-auction-app-d2984',
    authDomain: 'ipl-auction-app-d2984.firebaseapp.com',
    storageBucket: 'ipl-auction-app-d2984.firebasestorage.app',
    measurementId: 'G-2YCXBCX8L5',
  );

}